name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/templated-bot:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Stop GCP VM
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCE_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCE_SA_KEY }}
        with:
          args: compute instances stop ${{ secrets.GCE_INSTANCE_NAME }} --zone ${{ secrets.GCE_ZONE }}
      -
        name: Start GCP VM
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCE_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCE_SA_KEY }}
        with:
          args: compute instances start ${{ secrets.GCE_INSTANCE_NAME }} --zone ${{ secrets.GCE_ZONE }}
